### ISSUE TITLE
RFE: port to fuse3

### ISSUE THREAD

**Issue by kloczek** [ostreedev/ostree#2191] opened 2020-09-05 00:52 UTC
To minimise tooling used in typical distribution it would be nice to move to fuse3 https://github.com/libfuse/libfuse/

**Comment by lucab** [comment] 2022-01-17 14:34
Duplicate of https://github.com/ostreedev/ostree/issues/1881, fixed by https://github.com/ostreedev/ostree/pull/2376 in `2022.1`, closing.

**Closed by lucab** 2022-01-17 14:34 UTC
