### ISSUE TITLE
`ostree admin status` can't check GPG signature unless key is imported first

### ISSUE THREAD

**Issue by miabbott** [ostreedev/ostree#1770] opened 2018-10-31 18:25 UTC
Using Fedora 29 AH, I observed that `rpm-ostree` will report that a commit is signed with a valid key, but `ostree admin status` does not until the key is imported.

```
# rpm -q ostree rpm-ostree
ostree-2018.8-1.fc29.x86_64
rpm-ostree-2018.8-1.fc29.x86_64

# cat /etc/ostree/remotes.d/fedora-atomic.conf
[remote "fedora-atomic"]
url=https://dl.fedoraproject.org/atomic/repo/
gpg-verify=true
gpgkeypath=/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-29-primary

# rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora-atomic:fedora/29/x86_64/atomic-host
                   Version: 29.20181030.0 (2018-10-30 15:35:06)
                    Commit: a4cfae321d662d84a7b8c59b59678af5eea0d89c9077affa77331c09341a5278
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4

# ostree admin status
* fedora-atomic a4cfae321d662d84a7b8c59b59678af5eea0d89c9077affa77331c09341a5278.0
    Version: 29.20181030.0
    origin refspec: fedora-atomic:fedora/29/x86_64/atomic-host
    GPG: Signature made Tue 30 Oct 2018 03:35:17 PM UTC using RSA key ID A20AA56B429476B4
    GPG: Can't check signature: public key not found

# ostree remote gpg-import fedora-atomic -k /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-29-primary                                                                                            
Imported 1 GPG key to remote "fedora-atomic"

# ostree admin status
* fedora-atomic a4cfae321d662d84a7b8c59b59678af5eea0d89c9077affa77331c09341a5278.0
    Version: 29.20181030.0
    origin refspec: fedora-atomic:fedora/29/x86_64/atomic-host
    GPG: Signature made Tue 30 Oct 2018 03:35:17 PM UTC using RSA key ID A20AA56B429476B4
    GPG: Good signature from "Fedora 29 <fedora-29@fedoraproject.org>"
```

**Comment by dustymabe** [comment] 2018-11-01 17:15
In other words.. it seems like `ostree admin status` is not respecting the `gpgkeypath` from the remote configuration in `/etc/ostree/remotes.d/` ?

**Comment by miabbott** [comment] 2018-11-01 18:37
I guess so, but I would have thought `rpm-ostree` was just using `libostree` for its GPG verification.

**Comment by dustymabe** [comment] 2018-11-05 17:56
i can reproduce on f29AH vagrant box:

```
[vagrant@vanilla-f29-atomic ~]$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora-atomic:fedora/29/x86_64/atomic-host
                   Version: 29.20181025.1 (2018-10-25 14:46:54)
                    Commit: 4a999b4b303b47468ff1464051a14fd075d2e7b8bb647584b7cc80fed48cf27b
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4
[vagrant@vanilla-f29-atomic ~]$ 
[vagrant@vanilla-f29-atomic ~]$ ostree admin status
* fedora-atomic 4a999b4b303b47468ff1464051a14fd075d2e7b8bb647584b7cc80fed48cf27b.0
    Version: 29.20181025.1
    origin refspec: fedora-atomic:fedora/29/x86_64/atomic-host
    GPG: Signature made Thu 25 Oct 2018 02:47:04 PM UTC using RSA key ID A20AA56B429476B4
    GPG: Can't check signature: public key not found

```

**Comment by dustymabe** [comment] 2018-11-08 16:36
Assuming this has worked in the past and hasn't been broken forever, I suspect this is an easy fix, marking as such.

**Comment by cgwalters** [comment] 2018-11-08 16:53
It's because `ot-admin-builtin-status.c` needs to be updated to call `ostree_repo_verify_commit_for_remote()`.

**Comment by dustymabe** [comment] 2018-11-08 17:59
thanks @cgwalters - that's good info for someone new

@Marcel-Lambacher - you interested in another somewhat easy issue?

**Comment by Marcel-Lambacher** [comment] 2018-11-08 20:18
Yeah of course. Just give me a bit more time. I’ll have a look this weekend :)

**Comment by r4f4** [comment] 2018-12-12 12:24
@Marcel-Lambacher are you still working on this?

**Comment by r4f4** [comment] 2018-12-12 15:43
@dustymabe yes. It looks like a good first issue for me.

**Comment by ashcrow** [comment] 2018-12-12 15:52
COREOS-899

**Comment by dustymabe** [comment] 2018-12-13 15:21
assigned to @r4f4 - thanks @r4f4

**Closed** 2018-12-14 15:38 UTC
Labels: bug, good-first-issue
