### ISSUE TITLE
ostree creates partial commits when pulling locally from consistent archive repo into bare-user

### ISSUE THREAD

**Issue by clime** [ostreedev/ostree#2011] opened 2020-02-17 01:46 UTC
Hello,

i have an mode=archive repo with 15 commits, which passes fsck check:
```
clime@den ~/export-repo $ ostree fsck
Validating refs...
Validating refs in collections...
Enumerating objects...
Verifying content integrity of 15 commit objects...
fsck objects (185259/185259) [=============] 100%
```

Then when i try to import it into bare-user repo, something strange happens (i run under root with selinux disabled so that i know for sure it is not a permission issue):

```
root@den /home/clime $ ostree init --repo=repo --mode=bare-user
root@den /home/clime $ cd repo
root@den /home/clime/repo $ ostree pull-local --depth=-1 ../export-repo
22802 metadata, 162457 content objects imported 

$ ls state/*
state/0f2341be23e34a077630a0309e50419716c6c941045d6c522c60ec772833c0e8.commitpartial
state/150e4bd9c752106941f6706769e8c9ebaba27fcf0c80e4524f7c1f57e7269a99.commitpartial
state/25a62cc62b4a06ececc325503f6a7682118e9df7174b508ac8a19f4f6b0c2658.commitpartial
state/25aeddf96558b335d3a199758a24688298375eaf9effdd81b644871cf3b83ef2.commitpartial
state/5dafc7e2ef259e0ff95a61c4e51b79e43f93e83ff91b5a90efda0609ccacf196.commitpartial
state/648d8869c8095a813cf90c45ebb3580bd78d6e122a2b7871947ecd89b8dd079f.commitpartial
state/669030aab33cce64c200b1f0b25d8786c541fe63c97791a87f9024b986760d80.commitpartial
state/841cd523a5a4543023fe4d759a2d696c7740218df7a6dde20171929b22d13734.commitpartial
state/8bc54811db6b553b6b43fa06499b845a11d275d98988be87793a48cc0f43785d.commitpartial
state/ae13f531cae26bc55e3009e863787f8829b8c6a6aeadbee8abcdbe931aa6fedd.commitpartial
state/b4ce23168f9c557810cb13f5b926cf17b92f3f3356c7ca8e32ee01f33f269d45.commitpartial
state/b5533b7e442646adc66c0f1c9fa755f5a3a7b9ce3b77673c8c25533b0a398ffd.commitpartial
state/ba82a02bcd23dbd8e366659f16387dc87ab73e90f1b68dacf8aafc32916e32a1.commitpartial
state/bed843df8b5c70552ef934b56942b592085e562c2314de18525f4984354b2e70.commitpartial
```

If I, however, remove those files and run fsck, it succeeds:

```
root@den /home/clime/repo $ rm state/*
root@den /home/clime/repo $ ostree fsck
Validating refs...
Validating refs in collections...
Enumerating objects...
Verifying content integrity of 15 commit objects...
fsck objects (185259/185259) [=============] 100%

```

Should I be worried about these files?

**Comment by jlebon** [comment] 2020-03-19 14:55
Yes, this is most definitely a dupe of #2035.

**Closed by jlebon** 2020-03-19 14:55 UTC
