### ISSUE TITLE
kernel command line arguments do not get updated

### ISSUE THREAD

**Issue by jlarsen45** [ostreedev/ostree#2050] opened 2020-04-01 18:16 UTC
I am using intel-corei7-64 with grub2 as bootloader and using libostree through meta-updater ( ostree_2020.2.bb). If I change my kernel command line parameters the changes do not get updated when an update is performed.

Steps:

    1. make image with Yocto project.
    2. run image on board
    3. view kernel parameters cat /proc/cmdline
    4. change kernel command line parameters (OSTREE_KERNEL_ARGS)
    5. make new image within Yocto project.
    6. update board
    7. view kernel parameters cat /proc/cmdline

Expected result: command line parameters are the new parameters from new OSTREE_KERNEL_ARGS

Actual result: command line parameters are stuck at initial values

**Comment by patrickvacek** [comment] 2020-04-02 07:09
This looks to be a duplicate of https://github.com/advancedtelematic/meta-updater/issues/706, and the issue looks to be specific to meta-updater, not ostree, so I think this can be closed.

**Comment by cgwalters** [comment] 2020-04-02 12:07
Thanks; I think this is really a duplicate of https://github.com/ostreedev/ostree/issues/479 right?

Either way we agree it's a dup so closing, but nevertheless thanks for the report (and I also appreciate the triage too!)

**Closed by cgwalters** 2020-04-02 12:07 UTC
