### ISSUE TITLE
rpm-ostree status shows error fetching image metadata after ostree container image deploy

### ISSUE THREAD

**Issue by javipolo** [ostreedev/ostree#3002] opened 2023-08-23 11:52 UTC
I'm using `ostree container image deploy` to deploy an OCI I created in another host, and after that rpm-ostree cannot show the proper origin for that deployment:

```
[root@sno ~]# ostree container image deploy --sysroot / --stateroot javipolo --imgref ostree-unverified-registry:quay.io/whatever/ost:base                                           
note: Deploying commit 37e782164fe470be0059069a76b0f0f98c6a73fef392179cd8f0b373f04ee4ca which contains content in /var/lib that will be ignored.

[root@sno ~]# rpm-ostree status
State: idle
Deployments:
  (error fetching image metadata)
                Timestamp: 2023-08-23T07:13:18Z
                StateRoot: javipolo
      RemovedBasePackages: kernel-modules-core kernel-modules-extra kernel-core kernel kernel-modules 5.14.0-284.23.1.el9_2
          LayeredPackages: kernel-rt-core kernel-rt-kvm kernel-rt-modules kernel-rt-modules-extra

● ostree-unverified-registry:quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:87230f7f44e28fb137822bed659de5cedf338a79a9ed7456fd747a47ad84cc95
                   Digest: sha256:87230f7f44e28fb137822bed659de5cedf338a79a9ed7456fd747a47ad84cc95
                  Version: 414.92.202307250657-0 (2023-08-20T22:24:50Z)
                StateRoot: rhcos
```

Checking the .origin file for that deployment, I see that it has a `docker://` there, that if I manually remove, solves the issue:

```
[root@sno ~]# cat /ostree/deploy/javipolo/deploy/37e782164fe470be0059069a76b0f0f98c6a73fef392179cd8f0b373f04ee4ca.0.origin 
[origin]
container-image-reference=ostree-unverified-image:docker://quay.io/whatever/ost:base

[root@sno ~]# sed -e 's%docker://%%g' -i /ostree/deploy/javipolo/deploy/37e782164fe470be0059069a76b0f0f98c6a73fef392179cd8f0b373f04ee4ca.0.origin

[root@sno ~]# cat /ostree/deploy/javipolo/deploy/37e782164fe470be0059069a76b0f0f98c6a73fef392179cd8f0b373f04ee4ca.0.origin 
[origin]
container-image-reference=ostree-unverified-image:quay.io/whatever/ost:base

[root@sno ~]# rpm-ostree status
State: idle
Deployments:
  ostree-unverified-image:quay.io/whatever/ost:base
                Timestamp: 2023-08-23T07:13:18Z
               BaseCommit: 87e23501e8e6a2bc7bc06a3b2804f3fd72be37c4c2fe6d29d3683825c353b023
                StateRoot: javipolo
      RemovedBasePackages: kernel-modules-core kernel-modules-extra kernel-core kernel kernel-modules 5.14.0-284.23.1.el9_2
          LayeredPackages: kernel-rt-core kernel-rt-kvm kernel-rt-modules kernel-rt-modules-extra

● ostree-unverified-registry:quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:87230f7f44e28fb137822bed659de5cedf338a79a9ed7456fd747a47ad84cc95
                   Digest: sha256:87230f7f44e28fb137822bed659de5cedf338a79a9ed7456fd747a47ad84cc95
                  Version: 414.92.202307250657-0 (2023-08-20T22:24:50Z)
```

**Comment by cgwalters** [comment] 2023-08-23 18:29
Can you give a bit more step-by step cleaned up reproduction for this?  I can make some guesses but it'd help to have concrete steps.  For example, is what's in `quay.io/whatever/ost:base` actually relevant?  Or is it a standin for "any image"?

Does this actually relate to the kernel-rt override or not?

> Checking the .origin file for that deployment, I see that it has a docker:// there, that if I manually remove, solves the issue:

That's just confusing (rpm-)ostree into thinking it's not using a container at all I think...

**Comment by javipolo** [comment] 2023-08-23 22:17
The context is trying to transfer an OCP with rt-kernel on host A into host B. This is what I do:

> What specific OS versions are being used here as a starting point?
`Host A` is an `Openshift 4.13.5` with rt kernel
`Host B` is `Openshift 4.14.0`

> Can you give a bit more step-by step cleaned up reproduction for this? I can make some guesses but it'd help to have concrete steps. For example, is what's in `quay.io/whatever/ost:base` actually relevant? Or is it a standin for "any image"?
`quay.io/whatever/ost:base` is an image that I created with `ostree container encapsulate` pointing to the booted checksum commit on Host A

Those are the steps I follow:
## Host A
```
# Get booted commit
base_commit=$(rpm-ostree status -v --json | jq -r '.deployments[] | select(.booted == true).checksum')
# Encapsulate it into an image
ostree container encapsulate $base_commit registry:quay.io/whatever/ost:base --repo /ostree/repo --label ostree.bootable=true

# Get and also encapsulate the parent baseCommit
parent_commit=$(rpm-ostree status -v --json | jq -r '.deployments[] | select(.booted == true)."base-checksum"')
ostree container encapsulate $parent_commit registry:quay.io/whatever/ost:parent  --repo /ostree/repo --label ostree.bootable=true
```

## Host B
On host B, I start importing the parent baseCommit
```
mount /sysroot -o remount,rw

# Import parent baseCommit
ostree container unencapsulate --repo /ostree/repo ostree-unverified-registry:quay.io/whatever/ost:parent --write-ref parent

# Create new stateroot
ostree admin os-init javipolo
# Deploy the commit that was running (and includes rt-kernel)
ostree container image deploy --sysroot / --stateroot javipolo --imgref ostree-unverified-registry:quay.io/whatever/ost:base
```

After that, I would expect that `rpm-ostree status` shows `quay.io/whatever/ost:base` as deployed, and it shows, but complains about the `error fetching metadata` instead of displaying the name of the imported image:
```
[root@sno ~]# rpm-ostree status
State: idle
Deployments:
  (error fetching image metadata)
                Timestamp: 2023-08-23T07:13:18Z
                StateRoot: javipolo
      RemovedBasePackages: kernel-modules-core kernel-modules-extra kernel-core kernel kernel-modules 5.14.0-284.23.1.el9_2
          LayeredPackages: kernel-rt-core kernel-rt-kvm kernel-rt-modules kernel-rt-modules-extra

● ostree-unverified-registry:quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:87230f7f44e28fb137822bed659de5cedf338a79a9ed7456fd747a47ad84cc95
                   Digest: sha256:87230f7f44e28fb137822bed659de5cedf338a79a9ed7456fd747a47ad84cc95
                  Version: 414.92.202307250657-0 (2023-08-20T22:24:50Z)
                StateRoot: rhcos
```

> Does this actually relate to the kernel-rt override or not?
Yes, that's exactly the case

> > Checking the .origin file for that deployment, I see that it has a docker:// there, that if I manually remove, solves the issue:
> That's just confusing (rpm-)ostree into thinking it's not using a container at all I think...

I assume that doing this is not the way, but I thought it was worth mentioning that this change fixed the `rpm-ostree status` output :)

Also I discovered that machine-config-operator does not like the docker:// format either. The node is marked as Degraded and in machine.config-daemon I can see the error:
```
E0823 22:14:56.342181   35669 writer.go:200] Marking Degraded due to: Error checking type of update image: error parsing image name "docker://quay.io/jpolo/ostmagic:base": invalid reference format
```

That error goes away if I use the non docker:// format for the image

**Comment by cgwalters** [comment] 2023-08-28 21:40
There's a fair bit going on here.  What you're doing is IMO a somewhat special case of a much higher level flow of something like `rpm-ostree ex system-capture --save --exclude=/etc/hostname --exclude=/var/log quay.io/example/mysystem` for example that would serialize all of the system state to a container image, and we have the inverse operation `rpm-ostree ex system-capture --restore quay.io/example/mysystem --stateroot=alt` to restore.  Supporting kernel arguments will be important here.

The special case - and of course, this is very special is that we're actually just after a "local clone" where we can be a lot more efficient.

In the general case we have multiple refs we need to transport - in the ostree-container flow, each layer is stored as a ref.  If we don't write those on the other end, we'll end up needing to re-fetch them.

This is also true of layered packages (in the kernel-rt case) - rpm-ostree serializes the packages as ostree commits too, and if those aren't present we'll need to re-fetch them for upgrades.

The only reason it's working as much as it is is because the two stateroots intrinsically share the ostree repo.

**Comment by cgwalters** [comment] 2023-08-28 21:41
> Also I discovered that machine-config-operator does not like the docker:// format either. The node is marked as Degraded and in machine.config-daemon I can see the error error parsing image name "docker://quay.io/whatever/ost:base": invalid reference format:

xref https://github.com/openshift/machine-config-operator/pull/3857

But note though again what you're doing here just tricks rpm-ostree into not understanding it's fetching a container at all, which is not what we want I think.

**Comment by javipolo** [comment] 2023-08-29 08:01
If that `rpm-ostree` command existed, probably that would be a better fit to do this kind of "OS relocation"

In any case, with this kind of operation, I would like to keep upgrades to be pulling from the "official channels" that the original OS had, and I was wondering if that's enough of a valid use-case to have something like `ostree container image deploy --origin quay.io/openshift-release-dev/ocp@sha256:blah quay.io/whatever/ost:my_base_backup`

As of now I'm just manually replacing the origin with the original origin that was in the OS where I made the backup

**Comment by javipolo** [comment] 2023-08-30 09:53
> This already exists, see `--target-imgref`.

it does not work for me .... I want to mimic the origin file that OCP 4.13.5 has, so I issue this command to deploy my backup:
```
ostree container image deploy --sysroot / --stateroot ingrade --authfile /tmp/backup-secret.json --imgref ostree-unverified-registry:quay.io/whatever/ost:base --target-imgref ostree-unverified-registry:quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:64e718da9e357a00954fbb52d0aebd121ba8352812461b65ca2380d92dd50a8c
```

But then the `.origin` is created with a different syntax for the container-image-reference:
```
[origin]
container-image-reference=ostree-unverified-image:docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:64e718da9e357a00954fbb52d0aebd121ba8352812461b65ca2380d92dd50a8c
```

And rpm-ostree keeps reporting `error fetching metadata`:
```
State: idle
Deployments:
  (error fetching image metadata)
                Timestamp: 2023-08-28T14:41:44Z
                StateRoot: ingrade
      RemovedBasePackages: kernel-modules-core kernel-modules-extra kernel-core kernel kernel-modules 5.14.0-284.23.1.el9_2
          LayeredPackages: kernel-rt-core kernel-rt-kvm kernel-rt-modules kernel-rt-modules-extra
```

For reference, that's how a

**Comment by cgwalters** [comment] 2023-10-04 12:52
I think there's more steps to the reproducer here; I'm pretty sure this is related to the kernel-rt override right?  To be clear can you reproduce a problem without kernel-rt?

**Comment by cgwalters** [comment] 2023-10-04 13:14
I think what would help me here at some point is to just get an interactive shell in a system in this state, I can try to look at that on my own but if you can find a time to get me one that'd help

**Comment by javipolo** [comment] 2023-10-04 18:03
I've been trying to create an environment to reproduce this, and I seem to be unable to do it ....

Doing the same steps as before I cannot reproduce it now, I tried both rt kernel and non rt kernel (I'm quite sure that before this problem happent with both versions), just changing the origin file did the trick before ....

I can see the RHCOS version differs even if the OCP version is the same ... I dont know if something could have been patched in rpm-ostree/ostree affecting that :shrug:

I guess we can close this as it's no longer happening

**Comment by travier** [comment] 2024-03-25 10:00
Closing as per the reporter it's not longer reproductible and it's been a while. Thanks for the report and investigation.

**Closed by travier** 2024-03-25 10:00 UTC
Labels: reward/medium, area/container
