### ISSUE TITLE
Pull Request #2358 broke Yocto builds using ostree or any other system that reference master branch

### ISSUE THREAD

**Issue by jlarsen45** [ostreedev/ostree#2381] opened 2021-06-18 22:14 UTC
Yocto and probably other systems reference ostree by a branch and commit.  If you change the branch name then the fetch fails.  I understand that these systems could change to just look at commit id, but it also seems that this PR could have been crafted to keep the old branch name if at least for reference by these systems until they can change.

**Comment by lucab** [comment] 2021-06-20 09:20
This is a duplicate of https://github.com/ostreedev/ostree/issues/2360.

The branch deletion was re-enacted after feedback from the the Yocto project architect, see https://github.com/ostreedev/ostree/issues/2360#issuecomment-852377716 for all the details.

**Closed by lucab** 2021-06-20 09:20 UTC
