### ISSUE TITLE
An internet hiccup isn't ever a reasonable cause to abort

### ISSUE THREAD

**Issue by ell1e** [ostreedev/ostree#3033] opened 2023-09-07 05:03 UTC
I see flatpak regularly abort due to "stream error", "partial file", other clearly connection-related things, and then seemingly performing the cardinal sin on top of things which is to even just throw everything away it already downloaded (edit: actually, maybe it only does that through GNOME Software, I'm not entirely sure, with the cli it's not always entirely clear what's freshly downloaded). In any case, can you imagine if e.g. Valve's Steam for games did that? The only reasonable behavior for an internet error should be to at most to print a warning if at all, but to then continue retrying *and resuming* silently without any user interaction in perpetuity until the download works again and is completed. Neither pausing, nor fully aborting, nor throwing anything away feels like a reasonable response to internet errors.

I'm seeing [suggestions to use aria2](https://github.com/ostreedev/ostree/issues/2741) for this, although it seems to possibly bring other unwanted behaviors like parallel downloads [which by default is probably a bad idea](https://github.com/flatpak/flatpak/issues/5231). Therefore, I'm filing this more general ticket.

**Tested flatpak version that is affected by the unreasonable behavior:** 1.14.4

**Tested on linux distribution:** openSUSE Leap 15.5

**Comment by ericcurtin** [comment] 2023-09-07 09:54
That's a really detailed bug report in flatpak, great to see. On ostree-based transport in general, the focus is on enhancing OCI based transport at present as an alternate transport protocol:

https://coreos.github.io/rpm-ostree/container/

rather than aria2 client/server based transport. OCI based transport has been operating at scale and has many of the same requirements.

That's more a general comment than this use case specifically though.

**Comment by cgwalters** [comment] 2023-09-07 11:21
Hi, I believe this is a duplicate of https://github.com/ostreedev/ostree/issues/2570

**Closed by cgwalters** 2023-09-07 11:21 UTC
